version: 2

builds:
  - main: ./cmd/semconv-proxy
    binary: semconv-proxy
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE

sboms:
  - artifacts: archive

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
