version: 2

builds:
  - main: ./cmd/semconv-proxy
    binary: semconv-proxy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE
      - deployments/helm/semconv-proxy/**
    format_overrides:
      - goos: windows
        format: zip

sboms:
  - artifacts: archive
    documents:
      - "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.spdx.sbom.json"
    cmd: syft
    args: ["$artifact", "--output", "spdx-json", "--file", "$document"]

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - merge conflict
      - Revert
      - '^chore:'

dockers:
  - image_templates:
      - "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}-amd64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
  - image_templates:
      - "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}-arm64"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

docker_manifests:
  - name_template: "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}"
    image_templates:
      - "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}-amd64"
      - "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}-arm64"
  - name_template: "ghcr.io/henrikrexed/semconv-proxy:latest"
    image_templates:
      - "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}-amd64"
      - "ghcr.io/henrikrexed/semconv-proxy:{{ .Version }}-arm64"

release:
  github:
    owner: henrikrexed
    name: semconv-proxy
  mode: replace
