apiVersion: v2
name: semconv-proxy
description: Collector Semantic Convention Proxy - auto-discovers OTel semantic conventions
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - opentelemetry
  - otel
  - semconv
  - proxy
  - observability
home: https://github.com/henrikrexed/semconv-proxy
sources:
  - https://github.com/henrikrexed/semconv-proxy
maintainers:
  - name: henrikrexed
license: Apache-2.0
